##
##    This YAML file can be used to provision a minimal Tanzu Kubernetes cluster.
##
##    Provision within a vSphere namespace called "tkgs-cluster-ns" with: kubectl apply -f Tanzu_K8s_cluster_min.yml
##
---
apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-cluster-1
  namespace: tkgs-cluster-ns
spec:
  settings:
    network:
      cni:
        name: antrea
  topology:
    controlPlane:
      replicas: 1
      storageClass: vsan-default-storage-policy
      tkr:
        reference:
          name: v1.27.6---vmware.1-fips.1-tkg.1
      vmClass: best-effort-small
    nodePools:
    - name: workers
      replicas: 1
      storageClass: vsan-default-storage-policy
      vmClass: best-effort-small