##
##    Project: SDDC.Lab
##    Authors: Luis Chanu & Rutger Blom
##   Filename: requirements.yml
##
---
collections:
  - name: community.general
  - name: community.vmware
    version: 2.9.1
  - name: community.crypto
  - name: vyos.vyos
    version: 3.0.1
  - name: ansible.posix
  - name: git+https://github.com/vmware/ansible-for-nsxt.git,v3.2.0
  - name: vmware.alb
