##
##    Project: SDDC.Lab
##    Authors: Luis Chanu & Rutger Blom
##   Filename: requirements.yml
##
---
collections:
  - community.general
  - community.vmware
  - community.crypto
  - vyos.vyos
  - ansible.posix
  - git+https://github.com/vmware/ansible-for-nsxt.git,v3.2.0
  - vmware.alb

