##
##      Project: SDDC.Lab
##      Authors: Luis Chanu & Rutger Blom
##     Filename: utils/Util_CreateSoftwareDir.yml
##
##  Description: This utility performs the following functions:
##                 1) It creates the /Software folder structure
##                 2) It sets the folder permissions to 'rwxrwxrwx' on all directories
##
##               This utility utilizes Ansible's 'become' feature to escalate priviledges to 'root' user.
##               For that reason, it should NOT be run with 'sudo', and it should be executed as follows
##               from the root of the SDDC.Lab folder:
##
##                         ansible-playbook --ask-become-pass utils/Util_CreateSoftwareDir.yml
##
##               When you run the util as shown above, it will prompt you for the 'root' password.
##
---
- hosts: localhost
  name: Util_CreateSoftwareDir.yml
  vars_files:
    - ../software.yml
  tasks:

    - name: Create software.json with realized variables
      ansible.builtin.copy:
        content: "{{ lookup('template', '../software.yml') | from_yaml }}"
        dest: "{{ lookup('env', 'HOME') }}/software.json"
        mode: "775"

    - name: Read realized variables from software.json into playbook
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'HOME') }}/software.json"

    - name: Delete software.json file
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/software.json"
        state: absent

##
## Set Software Repository RootDirectory Permissions
##
    - name: Set permissions on {{ RootDirectory }}
      ansible.builtin.file:
        path: "{{ RootDirectory }}"
        state: directory
        mode: "0777"
      become: true

##
## VMware
##
    - name: Create VMware vCenter directories
      ansible.builtin.file:
        path: "{{ item.value.Location.Local }}"
        state: directory
        mode: "0777"
      become: true
      loop: "{{ Software.VMware.vCenter.Installers | dict2items }}"
      when: Software.VMware.vCenter.Installers is defined

    - name: Create VMware ESXi directories
      ansible.builtin.file:
        path: "{{ item.value.Location.Local }}"
        state: directory
        mode: "0777"
      become: true
      loop: "{{ Software.VMware.ESXi.Installers | dict2items }}"
      when: Software.VMware.ESXi.Installers is defined

    - name: Create VMware NSXT directories
      ansible.builtin.file:
        path: "{{ item.value.Location.Local }}"
        state: directory
        mode: "0777"
      become: true
      loop: "{{ Software.VMware.NSXT.Installers | dict2items }}"
      when: Software.VMware.NSXT.Installers is defined

    - name: Create VMware vRLI directories
      ansible.builtin.file:
        path: "{{ item.value.Location.Local }}"
        state: directory
        mode: "0777"
      become: true
      loop: "{{ Software.VMware.vRLI.Installers | dict2items }}"
      when: Software.VMware.vRLI.Installers is defined

    - name: Create VMware NSX Advanced Load Balancer directories
      ansible.builtin.file:
        path: "{{ item.value.Location.Local }}"
        state: directory
        mode: "0777"
      become: true
      loop: "{{ Software.VMware.ALB.Installers | dict2items }}"
      when: Software.VMware.ALB.Installers is defined

##
## Ubuntu
##
    - name: Create Ubuntu directories
      ansible.builtin.file:
        path: "{{ item.value.Location.Local }}"
        state: directory
        mode: "0777"
      become: true
      loop: "{{ Software.Ubuntu.Server.Installers | dict2items }}"
      when: Software.Ubuntu.Server.Installers is defined

##
## VyOS
##
    - name: Create VyOS directories
      ansible.builtin.file:
        path: "{{ item.value.Location.Local }}"
        state: directory
        mode: "0777"
      become: true
      loop: "{{ Software.VyOS.Router.Installers | dict2items }}"
      when: Software.VyOS.Router.Installers is defined
